apiVersion: v1
kind: Service
metadata:
  name: face-saas
  labels:
    app: face-saas-vkist
spec:
  type: LoadBalancer
  ports:
  - port: 85
    targetPort: 5000
    name: web
  selector:
    app: face-saas-vkist
