apiVersion: v1
kind: Pod
metadata:
  name: face-saas
  labels:
    app: face-saas-vkist
spec:
  containers:
  - name: face-saas-vkist
    image: daovietanh99/face_saas
    resources:
      requests:
        cpu: 8
        memory: "16G"
      limits:
        cpu: 8      
        memory: "16G"
    volumeMounts:
    - mountPath: /home/data/
      name: face-saas-volume
  - name: cache
    image: redis
    ports:
    - containerPort: 6379
      name: "cache"
    command: ["redis-server", "--port", "6379"]
  volumes:
  - name: face-saas-volume
    persistentVolumeClaim:
      claimName: face-saas-pvc
